/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyMeRouteImport } from './routes/why-me'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as EducationRouteImport } from './routes/education'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhyMeRoute = WhyMeRouteImport.update({
  id: '/why-me',
  path: '/why-me',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-me': typeof WhyMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-me': typeof WhyMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/skills': typeof SkillsRoute
  '/testimonials': typeof TestimonialsRoute
  '/why-me': typeof WhyMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/education'
    | '/experience'
    | '/skills'
    | '/testimonials'
    | '/why-me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/education'
    | '/experience'
    | '/skills'
    | '/testimonials'
    | '/why-me'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/education'
    | '/experience'
    | '/skills'
    | '/testimonials'
    | '/why-me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  SkillsRoute: typeof SkillsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WhyMeRoute: typeof WhyMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-me': {
      id: '/why-me'
      path: '/why-me'
      fullPath: '/why-me'
      preLoaderRoute: typeof WhyMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  SkillsRoute: SkillsRoute,
  TestimonialsRoute: TestimonialsRoute,
  WhyMeRoute: WhyMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
